[package]
name = "criptograficHash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# sha2 = "0.8.1"
sha2 = "*"
